### ISSUE TITLE
Authorisation error

### ISSUE THREAD

**Issue by kanchalwar** [BraydenNeale/Dynatrace-SNMP#10]
Hi Brayden

We're trying to receive SNMP traps from VMWare FlexManager. But we are getting below error -
Authorisation error(Device connection issue: check snmp access: No SNMP response received before timeout)
We believe everything is perfect, is there any compatibility issue?

Regards
Sandeep

**Comment by BraydenNeale** [comment]
Hi Sandeep,

I don't think this would be any compatibility issue. 
This error Just means that the device didn't respond to the SNMP query, possibly because it couldn't be reached over the network or the ActiveGate was in the access list.
Can you confirm that the ActiveGate is able to reach the Flexmanager over the network?

Thanks,
Brayden

**Comment by kanchalwar** [comment]
Hi Brayden

AG & FM are able to ping each other. Not sure telnet can validate SNMP
communication.

Best regards & thanks
Sandeep Kanchalwar
